# Generated by Django 5.1.3 on 2024-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(default='DEFAULT_CODE', max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_descript', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_unit', models.CharField(max_length=50)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_serialized', models.BooleanField(default=False)),
            ],
        ),
    ]
